### ISSUE TITLE
优化Mark Manager

### ISSUE THREAD

**Issue by Wlj2002** [joansnotion/NotionMate#4] opened 2024-04-09 14:51 UTC
目前的Mark Manager显示顺序是所有带颜色的文字标注优先显示，当它们全部显示完后，才会显示文字画线或高亮的内容。这不太符合连贯的阅读习惯。建议作者可以考虑优化成所有标注按文章中出现的顺序显示。辛苦了！

**Comment by joansnotion** [comment] 2024-04-09 16:30
Ok, the next version adds an option to support sequential display. Thank
you for your support!

Wlj2002 ***@***.***> 于2024年4月9日周二 22:51写道：

**Comment by joansnotion** [comment] 2024-04-09 16:31
Ok, the next version adds an option to support sequential display. Thank you for your support!

**Comment by joansnotion** [comment] 2024-04-10 02:48
The latest version, v1.7.7, supports Mark Mananger to display color text from top to bottom.

![image](https://github.com/joansnotion/NotionMate/assets/155308134/77354f74-f0bb-40f4-bbc0-477a3e6aee83)

**Comment by Wlj2002** [comment] 2024-04-10 02:57
What an executive author! It's worth the money.

**Comment by joansnotion** [comment] 2024-04-10 03:59
If the problem is solved, please close the issue.

**Closed** 2024-04-10 04:00 UTC
Labels: enhancement
